language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake python python-dev liblua5.2-dev ruby ruby-dev libperl-dev tcl-dev
- curl --silent https://polarssl.org/download/polarssl-1.3.9-gpl.tgz | tar xfz - && cd polarssl-1.3.9 && make SHARED=1 && sudo make install DESTDIR=/usr && cd ..

script: cmake . -DDEBUG=on -DUSE_TCL_PLUGIN=off -DUSE_RUBY_PLUGIN=off && cat config.h && make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li

    on_success: always
    on_failure: always
