before_install:
  - sudo apt-get install -qq python-dev ruby-dev libperl-dev liblua5.2-dev


language: c

compiler:
  - clang
  - gcc

install: make

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li
      - romain.coltel@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
