language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake python python-dev liblua5.2-dev ruby ruby-dev libruby1.9.1 libperl-dev tcl-dev
- curl --silent https://polarssl.org/download/polarssl-1.3.9-gpl.tgz | tar xfz - && cd polarssl-1.3.9 && make && sudo make install && cd ..

script: cmake . -DDEBUG=ON && make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li

    on_success: always
    on_failure: always
