language: c

os:
    - linux
    - osx

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
        compiler:
            - clang
            - gcc
            
      - os: osx
        osx_image: xcode7.3
        compiler: clang

    allow_failures:
      - os: osx

addons:
    apt:
      packages:
        - cmake
        - python-dev
        - liblua5.2-dev
        - ruby
        - ruby-dev
        - libperl-dev
        - tcl-dev
        - default-jdk

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install mbedtls; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -fSsL https://tls.mbed.org/download/mbedtls-2.2.0-gpl.tgz|tar xz && cd mbedtls-2.2.0 && cmake . -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_SHARED_LINKER_FLAGS="-pie" && make && sudo make install && cd .. ; fi
# - gem install package_cloud

script:
- cmake . -DDEBUG=on   && make && make clean
- cmake . -DDEBUG=off  && make && sudo make install

after_script:
- /opt/proxenet/bin/proxenet --help
# - package_cloud push hugsy/proxenet/debian/jessie proxenet-nightly-0.5-1_amd64.deb
# - package_cloud push hugsy/proxenet/fedora/23 proxenet-nightly.0.5-1.el6.x86_64.rpm

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat

    on_success: change
    on_failure: always
