language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq python-dev liblua5.2-dev ruby-dev libruby1.9.1 libperl-dev
- sudo apt-get install -qq -t testing libpolarssl-dev

script: PKG_CONFIG_PATH=`pwd`/pc/ make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li

    on_success: always
    on_failure: always
