language: c

os:
    - linux
    - osx

addons:
    apt:
      packages:
        - cmake
        - check
        - python-dev
        - liblua5.2-dev
        - ruby
        - ruby-dev
        - libperl-dev
        - tcl-dev
        - default-jdk

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install mbedtls check; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -fSsL https://tls.mbed.org/download/mbedtls-2.2.1-gpl.tgz|tar xz && cd mbedtls-2.2.1 && cmake . -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_SHARED_LINKER_FLAGS="-pie" && make && sudo make install && cd .. ; fi

script:
- cmake . -DDEBUG=on  && make && make test && sudo make install

after_script:
- /opt/proxenet/bin/proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat

    on_success: change
    on_failure: always
