language: c

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install -qq python-dev liblua5.2-dev libpolarssl-dev 

script: make FORCE_RUBY18=1

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - proxenet@pyc.li

    on_success: always
    on_failure: always
