language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake python python-dev liblua5.2-dev ruby ruby-dev libperl-dev tcl-dev default-jdk
- curl -fsSL https://github.com/ARMmbed/mbedtls/archive/mbedtls-1.3.13.tar.gz | tar xz && cd mbedtls-mbedtls-1.3.13 && cmake . -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_SHARED_LINKER_FLAGS="-pie" && sudo make install

script: cmake . -DDEBUG=on && make && make clean && cmake . -DDEBUG=off && make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat

    on_success: always
    on_failure: always
