language: c

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get install -qq python-dev liblua5.2-dev libpolarssl-dev

script: make

notifications:
  email:
    recipients:
      - hugsy+github@pyc.li
      - romain.coltel@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
