language: c

compiler:
  - clang
  - gcc

before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake python python-dev liblua5.2-dev ruby ruby-dev libperl-dev tcl-dev default-jdk
- curl -fSsL https://tls.mbed.org/download/mbedtls-2.2.0-gpl.tgz|tar xz && cd mbedtls-2.2.0 && cmake . && make && sudo make install && cd ..

script: cmake . -DDEBUG=on && make && make clean && cmake . -DDEBUG=off && make

after_script: ./proxenet --help

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat

    on_success: always
    on_failure: always
