site_name: proxenet documentation
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['compil.md', 'Compilation']
- ['config.md', 'Configuration']
- ['plugin.md', 'HowTo write plugins']
- ['runtime.md', 'Runtime']
- ['refs.md', 'References']
