site_name: proxenet documentation
theme: readthedocs
pages:
- [index.md, Home]
- [compil.md, Compilation]
- [config.md, Configuration]
- [plugin.md, HowTo write plugins]
- [plugins/index.md, Plugins]
- [plugins/perl.md, Perl]
- [plugins/java.md, Java]
- [plugins/ruby.md, Ruby]
- [plugins/c.md, C]
- [plugins/lua.md, Lua]
- [plugins/tcl.md, Tcl]
- [plugins/python.md, Python]
- [refs.md, References]
- [runtime.md, Runtime]
